version: '3'

services:
  postgres-database:
    image: postgres:16.0-alpine
    container_name: postgres-database
    env_file: ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # cherish-api:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.dev
  #   container_name: cherish-api
  #   env_file: ./.env
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres-database
  #   environment:
  #     DATABASE_URL: $DATABASE_URL